#!/bin/bash

# iOS Deployment Script
# Generated by fastlane_ios_setup.sh

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

# Load configuration
if [ -f "$PROJECT_ROOT/.ios_fastlane_config" ]; then
    source "$PROJECT_ROOT/.ios_fastlane_config"
fi

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo -e "${GREEN}🚀 iOS Deployment Script${NC}"
echo ""

# Load environment variables if .env file exists
if [ -f "$PROJECT_ROOT/.env" ]; then
    export $(cat "$PROJECT_ROOT/.env" | grep -v '^#' | xargs)
fi

ACTION=${1:-testflight}

# Navigate to iOS directory
cd "$PROJECT_ROOT/ios"

case "$ACTION" in
    testflight|beta)
        echo -e "${YELLOW}📱 Deploying to TestFlight...${NC}"
        fastlane beta
        ;;
    release|appstore)
        echo -e "${YELLOW}📱 Deploying to App Store...${NC}"
        fastlane release
        ;;
    build)
        echo -e "${YELLOW}🔨 Building IPA...${NC}"
        fastlane build
        ;;
    firebase)
        echo -e "${YELLOW}🔥 Distributing to Firebase...${NC}"
        fastlane firebase
        ;;
    *)
        echo -e "${RED}❌ Invalid action: $ACTION${NC}"
        echo "Usage: $0 [testflight|release|build|firebase]"
        exit 1
        ;;
esac

echo -e "${GREEN}✅ iOS deployment completed successfully!${NC}"
