#!/bin/bash

# iOS TestFlight Deployment Script
# Generated by fastlane_ios_setup.sh
# Usage: ./deploy_ios_testflight.sh [development|staging|production]

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

ENVIRONMENT=${1:-development}

echo -e "${GREEN}🚀 iOS TestFlight Deployment Script${NC}"
echo -e "${YELLOW}Environment: ${ENVIRONMENT}${NC}"
echo ""

# Navigate to iOS directory
cd "$PROJECT_ROOT/ios"

case "$ENVIRONMENT" in
    development|dev)
        echo -e "${YELLOW}📱 Deploying Development to TestFlight...${NC}"
        fastlane development
        ;;
    staging|stg)
        echo -e "${YELLOW}📱 Deploying Staging to TestFlight...${NC}"
        fastlane staging
        ;;
    production|prod)
        echo -e "${YELLOW}📱 Deploying Production to TestFlight...${NC}"
        fastlane production
        ;;
    release)
        echo -e "${YELLOW}📱 Deploying to App Store...${NC}"
        fastlane release
        ;;
    *)
        echo -e "${RED}❌ Invalid environment: $ENVIRONMENT${NC}"
        echo "Usage: $0 [development|staging|production|release]"
        exit 1
        ;;
esac

echo -e "${GREEN}✅ iOS deployment completed successfully!${NC}"
