#!/bin/bash

# Simple script to set up Xcode for Flutter flavors
# This will guide you through the manual steps

set -e

echo "========================================="
echo "iOS Flavor Setup for Flutter"
echo "========================================="
echo ""
echo "Your project is configured for 3 flavors:"
echo "  - development (bundle: com.pitangent.marketGpt.dev)"
echo "  - staging (bundle: com.pitangent.marketGpt.stg)"
echo "  - production (bundle: com.pitangent.marketGpt)"
echo ""
echo "The xcconfig files are already set up."
echo "Now we need to add build configurations to Xcode."
echo ""
echo "========================================="
echo "Option 1: Manual Setup (Recommended)"
echo "========================================="
echo ""
echo "1. Open Xcode:"
echo "   open ios/Runner.xcworkspace"
echo ""
echo "2. Select the 'Runner' PROJECT (not target) in the left sidebar"
echo ""
echo "3. Go to the 'Info' tab"
echo ""
echo "4. Under 'Configurations', duplicate each configuration for each flavor:"
echo ""
echo "   For Debug:"
echo "     - Click '+' under Debug"
echo "     - Select 'Duplicate Debug Configuration'"
echo "     - Name it: Debug-development"
echo "     - Set config file to: Development"
echo ""
echo "     - Repeat for: Debug-staging (Staging) and Debug-production (Production)"
echo ""
echo "   For Release:"
echo "     - Click '+' under Release"
echo "     - Select 'Duplicate Release Configuration'"
echo "     - Name it: Release-development"
echo "     - Set config file to: Development"
echo ""
echo "     - Repeat for: Release-staging (Staging) and Release-production (Production)"
echo ""
echo "   For Profile:"
echo "     - Click '+' under Profile"
echo "     - Select 'Duplicate Profile Configuration'"
echo "     - Name it: Profile-development"
echo "     - Set config file to: Development"
echo ""
echo "     - Repeat for: Profile-staging (Staging) and Profile-production (Production)"
echo ""
echo "5. Update Podfile configurations (already done):"
echo "   The Podfile has been updated with flavor configurations."
echo ""
echo "6. Run pod install:"
echo "   cd ios && export LANG=en_US.UTF-8 && pod install"
echo ""
echo "7. Try building:"
echo "   ./scripts/build_ipa_dev.sh"
echo ""
echo "========================================="
echo "Option 2: Automated Setup"
echo "========================================="
echo ""
echo "We can try to use fastlane or a Python script to automate this."
echo "Would you like to proceed with the manual setup? (Recommended)"
echo ""
